# Generated by Anaconda 36.16.5
# Generated by pykickstart v3.36
#version=F{{ version }}
# Use graphical install
graphical

# Keyboard layouts
keyboard --vckeymap=us --xlayouts='us'
# System language
lang en_US.UTF-8

# Network information
network  --bootproto=dhcp --device=eno1 --ipv6=auto --activate
network  --hostname=workstation

# Use network installation
url --url="http://{{ ansible_default_ipv4.address }}/f{{ version }}-inst.local/"

# Run the Setup Agent on first boot
firstboot --enable --reconfig
